// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test7.Models;

#nullable disable

namespace Test7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test7.Models.Dosen", b =>
                {
                    b.Property<string>("Nip")
                        .HasColumnType("NVarChar(12)");

                    b.Property<string>("Nama_Dosen")
                        .IsRequired()
                        .HasColumnType("NVarChar(25)");

                    b.HasKey("Nip");

                    b.ToTable("dosen");
                });

            modelBuilder.Entity("Test7.Models.Mahasiswa", b =>
                {
                    b.Property<string>("Nim")
                        .HasColumnType("NVarChar(9)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("NVarChar(25)");

                    b.Property<int>("Jenis_Kelamin")
                        .HasColumnType("int");

                    b.Property<string>("Nama_Mhs")
                        .IsRequired()
                        .HasColumnType("NVarChar(25)");

                    b.Property<DateOnly>("Tgl_Lahir")
                        .HasColumnType("date");

                    b.HasKey("Nim");

                    b.ToTable("mahasiswa");
                });

            modelBuilder.Entity("Test7.Models.Matakuliah", b =>
                {
                    b.Property<string>("Kode_MK")
                        .HasColumnType("NVarChar(6)");

                    b.Property<string>("Nama_MK")
                        .IsRequired()
                        .HasColumnType("NVarChar(20)");

                    b.Property<int>("Sks")
                        .HasColumnType("Int");

                    b.HasKey("Kode_MK");

                    b.ToTable("matakuliah");
                });

            modelBuilder.Entity("Test7.Models.Perkuliahan", b =>
                {
                    b.Property<int>("PerkuliahanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerkuliahanId"));

                    b.Property<string>("Kode_MK")
                        .IsRequired()
                        .HasColumnType("NVarChar(6)");

                    b.Property<string>("Nilai")
                        .IsRequired()
                        .HasColumnType("Char(1)");

                    b.Property<string>("Nim")
                        .IsRequired()
                        .HasColumnType("NVarChar(9)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("NVarChar(12)");

                    b.HasKey("PerkuliahanId");

                    b.HasIndex("Kode_MK");

                    b.HasIndex("Nim");

                    b.HasIndex("Nip");

                    b.ToTable("perkuliahan");
                });

            modelBuilder.Entity("Test7.Models.Perkuliahan", b =>
                {
                    b.HasOne("Test7.Models.Matakuliah", "Matakuliah")
                        .WithMany("Perkuliahan")
                        .HasForeignKey("Kode_MK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test7.Models.Mahasiswa", "Mahasiswa")
                        .WithMany("Perkuliahan")
                        .HasForeignKey("Nim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test7.Models.Dosen", "Dosen")
                        .WithMany("Perkuliahan")
                        .HasForeignKey("Nip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosen");

                    b.Navigation("Mahasiswa");

                    b.Navigation("Matakuliah");
                });

            modelBuilder.Entity("Test7.Models.Dosen", b =>
                {
                    b.Navigation("Perkuliahan");
                });

            modelBuilder.Entity("Test7.Models.Mahasiswa", b =>
                {
                    b.Navigation("Perkuliahan");
                });

            modelBuilder.Entity("Test7.Models.Matakuliah", b =>
                {
                    b.Navigation("Perkuliahan");
                });
#pragma warning restore 612, 618
        }
    }
}
